/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicsassignment;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author Prerna Dutta
 */
public class MovingFan extends javax.swing.JFrame {

    /**
     * Creates new form Graphics
     */
    public MovingFan() {
        initComponents();
        this.setVisible(true);
         this.getContentPane().setBackground(new java.awt.Color(168,51,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graphics Moving Fan");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        jButton1.setText("Click Me");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jEditorPane1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jEditorPane1.setForeground(new java.awt.Color(51, 51, 51));
        jEditorPane1.setText("Click This Button to    See the Effect of      Moving Fan.");
        jScrollPane2.setViewportView(jEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 79, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton1)
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Graphics2D gfx=(Graphics2D)jPanel1.getGraphics();
        gfx.setBackground(Color.WHITE);
        Matrix m1=new Matrix();
        Matrix m2=new Matrix();
        Matrix m3=new Matrix();
        Matrix m4=new Matrix();
        float[][] a={{1,0,0},{0,1,0},{-80,-80,1}};
        float[][] c={{1,0,0},{0,1,0},{80,80,1}};
        float[][] b={{(float)Math.cos(Math.toRadians(5)),(float)Math.sin(Math.toRadians(5)),0},{-(float)Math.sin(Math.toRadians(5)),(float)Math.cos(Math.toRadians(5)),0},{0,0,1}};
        float[][] d={{(float)Math.cos(Math.toRadians(120)),(float)Math.sin(Math.toRadians(120)),0},{-(float)Math.sin(Math.toRadians(120)),(float)Math.cos(Math.toRadians(120)),0},{0,0,1}};
        m1.m_data=a;
        m3.m_data=c;
        m2.m_data=b;
        m4.m_data=d;
        Matrix res=Matrix.multimatrix(m1, m2);
        res=Matrix.multimatrix(res, m3);
        Matrix res1=Matrix.multimatrix(m1, m4);
        res1=Matrix.multimatrix(res1, m3);
        Wings r=new Wings();
        float[][] pt={{90,70,1},{130,70,1},{130,90,1},{90,90,1}};
        r.wing1=pt;
        r.wing2=Matrix.Point2Matrix(r.wing1,res1);
        r.wing3=Matrix.Point2Matrix(r.wing2,res1);
        for(int i=0;i<500;i++){
           gfx.drawOval(70, 70, 20, 20);
           r.DrawRectangle(gfx);
           r=Wings.RotateWings(r,res);
        }
        /*gfx.drawLine(1,1,100,100);
        for(int i=0;i<=60;i=i+2){
           gfx.drawRect(10+i, 10, 50+i, 50+i);
           gfx.drawOval(200+i, 10, 110-i, 110-i);
           gfx.drawRect(10+i, 140, 110-i, 110-i);
           gfx.drawOval(200+i,140, 50+i, 50+i);
        }
        for(int i=0;i<=60;i=i+2){
           gfx.drawRect(70+i, 10, 110-i, 110-i);
           //gfx.drawRect(10, 10+i, 50, 50);
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovingFan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovingFan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovingFan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovingFan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MovingFan g=new MovingFan();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
